### ISSUE TITLE
Gradle task names are swapped

### ISSUE THREAD

**Issue by twyatt-fis** [DroidsOnRoids/android-animation-disabler#1]
Using `gradle.plugin.pl.droidsonroids.gradle:android-gradle-animation-disabler:1.0.1`.

Looks like the boolean check at [AnimationDisablerPlugin.kt#L38](https://github.com/koral--/android-animation-disabler/blob/master/src/main/kotlin/pl/droidsonroids/gradle/animation/AnimationDisablerPlugin.kt#L38) is reversed.

Currently reads:
```
tasks.create("connected${if (enableAnimations) "Dis" else "En"}ableAnimations") {
```

But should read:
```
tasks.create("connected${if (enableAnimations) "En" else "Dis"}ableAnimations") {
```

**Comment by koral--** [comment]
Fixed in 1.0.2.
Thanks for the report.
